# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: MR build and tests

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build backend application
      run: dotnet build --configuration Debug --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install
      working-directory: ./easyfinance.client

    - name: Run Angular tests
      run: npm test -- --watch=false --browsers=ChromeHeadless
      working-directory: ./easyfinance.client

    - name: Start application
      run: dotnet run --project ./EasyFinance.Server --urls https://localhost:7003/ &

    - name: Run Cypress tests
      run: npx cypress run
      working-directory: ./easyfinance.client